### ISSUE TITLE
This example does not use Impala JDBC connector

### ISSUE THREAD

**Issue by ManuelSchneid3r** [onefoursix/Cloudera-Impala-JDBC-Example#6]
You should explicitely point out that this example does NOT use [impala jdbc](http://www.cloudera.com/downloads/connectors/impala/jdbc/2-5-30.html), but hive jdbc.

An impala connection url  looks like "jdbc:impala://host:port" the one used in this project is "jdbc:hive2://host:port"

**Comment by onefoursix** [comment]
Hi Manuel -- Thank you for your comment.   At the time I wrote this an Impala connection URL was as described.  But with the new driver -- you're right!   I'll update the project to use the new impala URL

Thanks again

Mark

**Comment by onefoursix** [comment]
Fixed with new branch for Impala 2.3 and CDH5.5 and showing the new jdbc connection syntax
