### ISSUE TITLE
How do you capture Query that finishes with error and doesn't raise any exception?

### ISSUE THREAD

**Issue by mmpravish** [onefoursix/Cloudera-Impala-JDBC-Example#8]
Sometimes my query ends with an error like:

> ERROR: Query encountered invalid metadata, likely due to IMPALA-1702. Try rerunning the query.

This doesn't raise any exception but query really doesn't pass.

Also, in insert queries, we get a response in command like

> Inserted 18517844 row(s) in 238.88s

How do you capture that response with JDBC?

**Comment by onefoursix** [comment]
Sorry I do not know the answer to either question; you might have better luck posting the questions to the Cloudera Community Impala site here: http://community.cloudera.com/t5/Interactive-Short-cycle-SQL/bd-p/Impala
